import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useCallback, useEffect, useState } from "react";

export async function getStaticProps() {
  const data = await fetch("https://jsonplaceholder.typicode.com/todos").then(
    (res) => res.json()
  );
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const router = useRouter();

  const del = useCallback(
    ({ id }) => {
      fetch(`https://jsonplaceholder.typicode.com/todos/${id}`, {
        method: "Delete",
      }).then(() => {
        alert("Deleted!");
        router.push("/");
      });
    },
    [router]
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <button onClick={() => router.push("/add")}>Add New</button>

          {data?.map((x) => (
            <div className="item" key={x.id}>
              <h5>
                {x.id} - {x.title}
              </h5>
              <Link href={`/edit/${x.id}`}>Edit</Link>
              <br></br>
              <Link href="" onClick={() => del({ id: x.id })}>
                Delete
              </Link>
            </div>
          ))}
        </div>
        <style jsx>{`
          .item,
          .h5 {
            color: black;
          }
        `}</style>
      </main>
    </>
  );
}
